import config from "@sizeupdashboard/eslint-config/node";

export default [
  // Generated by `wrangler types`; not our code to lint.
  { ignores: ["worker-configuration.d.ts", "dist/**"] },
  ...config,
];
