import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@workspace/ui/styles/globals.css";
import { TCQueryProvider } from "@workspace/ui/providers/tc-query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-screen w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full h-full antialiased`}
      >
        <TCQueryProvider>
          {children}
        </TCQueryProvider>
      </body>
    </html>
  );
}
