import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@workspace/ui/styles/globals.css";
import "./globals.css";
import { TCQueryProvider } from "@workspace/ui/providers/convex-query-provider";
import { ThemeProvider } from "@workspace/ui/providers/theme-provider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { Toaster } from "@workspace/ui/components/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" className="dark h-screen w-full" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} w-full h-full antialiased`}
        >
          <TCQueryProvider>
            <ThemeProvider>
              {children}
              <Toaster />
            </ThemeProvider>
          </TCQueryProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
